### ISSUE TITLE
Not working with absinthe_plug 1.5.0

### ISSUE THREAD

**Issue by ramyma** [maartenvanvliet/apq#47]
I get this error when I try to fetch the deps:

```
Failed to use "absinthe_plug" (version 1.5.0) because   
 apq (version 1.2.0) requires ~> 1.4.6
```
Is it possible to bump up the version and release it on hex ?

**Comment by maartenvanvliet** [comment]
Pushed a new version with `absinthe_plug ~> 1.4`. That should resolve your issue.

**Comment by ramyma** [comment]
That was quick, thanks!
I suggest to update the read me and create a release on Github as it might be a bit confusing.
Your effort is very much appreciated :clap: :+1: 

Thanks again mate!

**Comment by ramyma** [comment]
On a side note- @maartenvanvliet v1.5 of **absinthe-graphql** was released lately https://github.com/absinthe-graphql/absinthe_plug/releases/tag/v1.5.0.

**Comment by maartenvanvliet** [comment]
Yes it should be compatible with both
