### ISSUE TITLE
Pretty print {:apq_stored, query}

### ISSUE THREAD

**Issue by fuelen** [maartenvanvliet/apq#92]
Hey, thank you for this awesome library.

Currently, queries are logged in 1 line and this is not very readable during development.
I'd suggest changing format from tuple-based to struct based and implement `Inspect` protocol on them, so Absinthe.Logger can nicely display it.

**Comment by maartenvanvliet** [comment]
Hey that seems like a good improvement. I don't know when I'll have time to look into it, PR welcome!

**Comment by maartenvanvliet** [comment]
pushed a 2.0.0 release that uses the Apq struct instead of a tuple, and implements the inspect protocol for some prettier printing

**Comment by fuelen** [comment]
@maartenvanvliet cool. Thank you!
I've tried a version from hex.pm, and I see the following error
```
** (UndefinedFunctionError) function Apq.Strategy.RawQuery.pipeline/2 is undefined (module Apq.Strategy.RawQuery is not available)
```
seems like the code is not up-to-date

**Comment by maartenvanvliet** [comment]
My bad, released a new version
